services:
  - type: web
    name: htksa-store
    root: ./htk-sa
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
